package lt.vu.usecases.mybatis.model;

public class Manufacturer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANUFACTURER.ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANUFACTURER.NAME
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANUFACTURER.ID
     *
     * @return the value of PUBLIC.MANUFACTURER.ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANUFACTURER.ID
     *
     * @param id the value for PUBLIC.MANUFACTURER.ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANUFACTURER.NAME
     *
     * @return the value of PUBLIC.MANUFACTURER.NAME
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANUFACTURER.NAME
     *
     * @param name the value for PUBLIC.MANUFACTURER.NAME
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}