package lt.vu.usecases.mybatis.model;

public class PhoneShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PHONE_SHOP.SHOP_ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PHONE_SHOP.PHONE_ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private Integer phoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PHONE_SHOP.SHOP_ID
     *
     * @return the value of PUBLIC.PHONE_SHOP.SHOP_ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PHONE_SHOP.SHOP_ID
     *
     * @param shopId the value for PUBLIC.PHONE_SHOP.SHOP_ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PHONE_SHOP.PHONE_ID
     *
     * @return the value of PUBLIC.PHONE_SHOP.PHONE_ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PHONE_SHOP.PHONE_ID
     *
     * @param phoneId the value for PUBLIC.PHONE_SHOP.PHONE_ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }
}