package lt.vu.usecases.mybatis.model;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.NAME
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.ID
     *
     * @return the value of PUBLIC.SHOP.ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.ID
     *
     * @param id the value for PUBLIC.SHOP.ID
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.NAME
     *
     * @return the value of PUBLIC.SHOP.NAME
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.NAME
     *
     * @param name the value for PUBLIC.SHOP.NAME
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.ADDRESS
     *
     * @return the value of PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.ADDRESS
     *
     * @param address the value for PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }
}