package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.PhoneShop;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PhoneShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE_SHOP
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    int deleteByPrimaryKey(@Param("shopId") Integer shopId, @Param("phoneId") Integer phoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE_SHOP
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    int insert(PhoneShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE_SHOP
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    List<PhoneShop> selectAll();
}