package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Phone;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    int insert(Phone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    Phone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    List<Phone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PHONE
     *
     * @mbg.generated Sun Mar 24 22:30:53 EET 2019
     */
    int updateByPrimaryKey(Phone record);

    List<Phone> selectByManufacturerId (Integer manufacturerId);
}