CREATE TABLE IF NOT EXISTS MANUFACTURER
(
	ID INTEGER NOT NULL IDENTITY,
	NAME            VARCHAR(50),
	OPT_LOCK_VERSION INTEGER,
	PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS PHONE
(
	ID INTEGER NOT NULL IDENTITY,
	MODEL           VARCHAR(50),
	PRICE           FLOAT,
	OPT_LOCK_VERSION INTEGER,
	MANUFACTURER_ID    INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (MANUFACTURER_ID) REFERENCES MANUFACTURER (ID)
);
CREATE TABLE IF NOT EXISTS SHOP
(
	ID INTEGER NOT NULL IDENTITY,
	NAME            VARCHAR(50),
	ADDRESS         VARCHAR(50),
	OPT_LOCK_VERSION INTEGER,
	PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS PHONE_SHOP
(
	SHOP_ID      INTEGER,
	PHONE_ID       INTEGER,
	PRIMARY KEY (SHOP_ID, PHONE_ID),
	FOREIGN KEY (SHOP_ID) REFERENCES SHOP (ID),
	FOREIGN KEY (PHONE_ID) REFERENCES PHONE (ID)
);

